### ISSUE TITLE
Algorithms for REACH / SURFACE / IMPACT / GEN. Centrality

### ISSUE THREAD

**Issue by dsr0018** [dsr0018/repo-net#14]

**Comment by dsr0018** [comment]
Gen. centrality interpretation should be revised with some new metric definitions. Implementation will be slightly delayed.

**Comment by clopezno** [comment]
To design an abstract class with the calculate method and a concrete class for each metric (REACH / SURFACE / IMPACT / GEN) seems to me a good design.
