### ISSUE TITLE
Mentor technical annexes  review

### ISSUE THREAD

**Issue by clopezno** [dsr0018/repo-net#29]
Attached is a pdf document with minor revision comments that aims to improve the understanding of the text.

Great job!
[anexos-revclopezno.pdf](https://github.com/dsr0018/olivia/files/5808560/anexos-revclopezno.pdf)

**Comment by dsr0018** [comment]
Done, thanks Carlos.
[anexos.pdf (revised)](https://app.zenhub.com/files/269325388/9ba94e1f-36f3-4dfc-a711-3907ea003bc3/download)
