### ISSUE TITLE
Revision documentación del sprint

### ISSUE THREAD

**Issue by clopezno** [dsr0018/repo-net#9]
La documentación resultado del sprint me parece muy buena. Se realiza una buena búsqueda bibliográfica donde se aclaran los conceptos de vulnerabilidad en redes de paquetes software desde el modelado de teoría de redes. 

El texto está bien escrito y todo es válido, pero quizás hay partes que hay que resumir y otras van más allá que una mera introducción y lo tenemos que distribuir en otras secciones de la memoria como la sección de objetivos. 

Adjunto el pdf con algunos comentarios de revisión 
[Vulnerabilidad_Redes_Dependencias_Memoria_clopezno.pdf](https://github.com/dsr0018/repo-net/files/4772682/Vulnerabilidad_Redes_Dependencias_Memoria_clopezno.pdf)

No te preocupes por la reestructuración y resumen, lo haremos en iteraciones futuras en alguna tarea de documentación de la memoria. 

El nombre del repositorio no me parece significativo "repo" vs "vulnerabilidad" 
"net" vs "net-packgsw".

**Comment by dsr0018** [comment]
La documentación se ha revisado. Queda pendiente incorporar una versión de trabajo al repositorio.
